server:
  port: 9191

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/museaAuthDB?createDatabaseIfNotExist=true
    username: root
    password: RG(SC$_7LxLU6f[N
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update